Repository Lee-Park-Bae-Project/KAKIOTALK, pull requests merged in 2020-07, with the labels that each got.

#127 [채팅방] 🚀 Infinite Scroll
  packages/client/src/common/request.ts
  packages/client/src/components/ChatBox/ChatBox.tsx
  packages/client/src/hooks/useIntersectionObserver.ts
  packages/client/src/modules/chat/reducer.ts
  packages/client/src/modules/profile/action.ts
  packages/client/src/modules/profile/reducer.ts
  packages/client/src/modules/room/action.ts
  packages/client/src/modules/room/types.ts
  packages/client/src/modules/sagas/chatSaga.ts
  packages/client/src/modules/sagas/roomSaga.ts
  packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
  packages/client/src/pages/chatroom/ChatArea/ChatList/ChatList.tsx
  packages/client/src/pages/chatroom/index.tsx
  packages/client/src/socket/socket.ts
  packages/client/src/system/UserList/index.tsx
  packages/client/src/types/index.ts
  packages/common/.eslintrc.js
  packages/common/src/types/apiTypes.ts
  packages/common/src/types/index.ts
  packages/common/src/types/socket.ts
  packages/server/src/common/error.ts
  packages/server/src/common/utils.ts
  packages/server/src/controllers/chat.ts
  packages/server/src/models/chat.ts
  packages/server/src/models/chatIsRead.ts
  packages/server/src/models/friends.ts
  packages/server/src/models/room.ts
  packages/server/src/models/roomParticipants.ts
  packages/server/src/models/user.ts
  packages/server/src/routes/v1/chat.route.ts
  packages/server/src/seeders/20200505152211-chats.js
  packages/server/src/services/chat.spec.ts
  packages/server/src/services/chat.ts
  packages/server/src/services/userService.spec.ts
Labels: API, BE, FE, enhancement

#133 [배포] 배포용 API 서버 주소 변경
  packages/client/src/common/constants.ts
Labels: API, BE, enhancement

#139 [채팅방] 🚀 스크롤 복구
  packages/client/src/common/request.ts
  packages/client/src/components/ChatBox/ChatBox.tsx
  packages/client/src/hooks/index.ts
  packages/client/src/hooks/useIntersectionObserver.ts
  packages/client/src/hooks/usePrevious.ts
  packages/client/src/modules/chat/action.ts
  packages/client/src/modules/chat/reducer.ts
  packages/client/src/modules/chat/types.ts
  packages/client/src/modules/sagas/chatSaga.ts
  packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
  packages/client/src/pages/chatroom/ChatArea/ChatList/ChatList.tsx
  packages/client/src/pages/chatroom/ChatArea/ChatList/styles.ts
  packages/client/src/pages/chatroom/index.tsx
  packages/client/src/socket/socket.ts
Labels: FE, enhancement

#136 [문서화] 📚 README 업데이트
  README.md
  docs/assets/infinite-scroll/can-i-use-intersection-observer.png
  docs/assets/infinite-scroll/infinite-scroll-demo.gif
  docs/assets/infinite-scroll/scroll-property.png
  docs/assets/nginx/forward-proxy.jpeg
  docs/assets/nginx/reverse-proxy.jpeg
  docs/infinite-scroll-with-intersection-observer.md
  docs/nginx.md
Labels: documentation

#137 [배포] Socket 연결 수정
  .travis.yml
  packages/client/src/common/constants.ts
Labels: bug

#141 [리팩토링] 소켓 로직 리덕스에 통합
  packages/client/src/modules/chat/action.ts
  packages/client/src/modules/sagas/index.ts
  packages/client/src/modules/sagas/roomSaga.ts
  packages/client/src/modules/sagas/socketSaga.ts
  packages/client/src/modules/socket/action.ts
  packages/client/src/modules/socket/index.ts
  packages/client/src/pages/chatroom/TextArea/TextArea.tsx
  packages/client/src/pages/chatroom/index.tsx
  packages/client/src/pages/main/index.tsx
  packages/client/src/socket/index.ts
  packages/client/src/socket/socket.ts
  packages/client/src/socket/types.ts
  packages/common/src/types/index.ts
  packages/common/src/types/socket.ts
  packages/server/src/socket/index.ts
Labels: FE, enhancement

#142 Redux state caching
  packages/client/.eslintrc.js
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/components/GoogleSignin/index.tsx
  packages/client/src/components/Loader/index.tsx
  packages/client/src/components/NavigationBar/LogoutTab/index.tsx
  packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
  packages/client/src/hooks/useAuth.ts
  packages/client/src/modules/chat/action.ts
  packages/client/src/modules/chat/reducer.ts
  packages/client/src/modules/chat/types.ts
  packages/client/src/modules/friends/action.ts
  packages/client/src/modules/friends/reducer.ts
  packages/client/src/modules/friends/types.ts
  packages/client/src/modules/index.ts
  packages/client/src/modules/login/action.ts
  packages/client/src/modules/login/reducer.ts
  packages/client/src/modules/login/types.ts
  packages/client/src/modules/profile/action.ts
  packages/client/src/modules/profile/reducer.ts
  packages/client/src/modules/profile/types.ts
  packages/client/src/modules/room/action.ts
  packages/client/src/modules/room/reducer.ts
  packages/client/src/modules/room/types.ts
  packages/client/src/modules/rootReducer.ts
  packages/client/src/modules/sagas/chatSaga.ts
  packages/client/src/modules/sagas/friendsSaga.ts
  packages/client/src/modules/sagas/index.ts
  packages/client/src/modules/sagas/loginSaga.ts
  packages/client/src/modules/sagas/profileSaga.ts
  packages/client/src/modules/store.ts
  packages/client/src/pages/chatroom/index.tsx
  packages/client/src/pages/main/Friend/index.tsx
  packages/client/src/pages/main/index.tsx
  packages/client/src/pages/main/styles.ts
  packages/client/src/system/Profile/index.tsx
  packages/client/src/system/Profile/styles.ts
  packages/server/.eslintrc.js
  packages/server/src/controllers/social.ts
  yarn.lock
Labels: FE, enhancement
