Repository Lee-Park-Bae-Project/KAKIOTALK, pull requests merged in 2020-08, with the labels that each got.

#155 [배포] vercel 로 client 배포
  .gitignore
  .travis.yml
  package.json
  packages/client/.storybook/addons.js
  packages/client/.storybook/config.js
  packages/client/.storybook/presets.js
  packages/client/.storybook/webpack.config.js
  packages/client/now.json
  packages/client/package.json
  packages/client/src/Icon/Icon.stories.tsx
  packages/client/src/atoms/Circle/Circle.stories.tsx
  packages/client/src/atoms/Hr/Hr.stories.tsx
  packages/client/src/atoms/Input/Input.stories.tsx
  packages/client/src/components/Button/button.stories.tsx
  packages/client/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/client/src/components/RoomCard/RoomCard.stories.tsx
  packages/client/src/components/TextIcon/TextIcon.stories.tsx
  packages/client/src/pages/chatroom/Header/Header.tsx
  vercel.json
Labels: FE

#166 🔨 [리팩토링] response type 통일 [WIP]
  packages/client/src/common/request.ts
  packages/client/src/common/utils.ts
  packages/client/src/components/Drawer/Drawer.tsx
  packages/client/src/components/GoogleSignin/index.tsx
  packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
  packages/client/src/hooks/useAuth.ts
  packages/client/src/modules/alert/action.ts
  packages/client/src/modules/alert/index.ts
  packages/client/src/modules/alert/reducer.ts
  packages/client/src/modules/alert/types.ts
  packages/client/src/modules/login/reducer.ts
  packages/client/src/modules/profile/action.ts
  packages/client/src/modules/room/reducer.ts
  packages/client/src/modules/rootReducer.ts
  packages/client/src/modules/sagas/chatSaga.ts
  packages/client/src/modules/sagas/friendsSaga.ts
  packages/client/src/modules/sagas/loginSaga.ts
  packages/client/src/modules/sagas/profileSaga.ts
  packages/client/src/modules/sagas/roomSaga.ts
  packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
  packages/client/src/pages/chatroom/ChatArea/ChatList/ChatList.tsx
  packages/client/src/pages/chatroom/Header/Header.tsx
  packages/client/src/pages/chatroom/index.tsx
  packages/client/src/pages/main/Friend/index.tsx
  packages/client/src/pages/main/index.tsx
  packages/client/src/system/Profile/index.tsx
  packages/client/src/system/Room/index.tsx
  packages/server/src/common/error.ts
  packages/server/src/common/utils.ts
  packages/server/src/controllers/auth.ts
  packages/server/src/controllers/social.ts
  packages/server/src/controllers/user.ts
  packages/server/src/middlewares/auth.ts
Labels: API, BE, FE, enhancement

#158 [배포] 클라이언트 자동배포
  .github/workflows/Deploy_Client.yml
  .github/workflows/client-stage-deploy.yml
  package.json
  packages/client/src/common/constants.ts
  packages/client/src/common/request.ts
  packages/client/src/components/GoogleSignin/index.tsx
  packages/server/src/configs/index.ts
Labels: FE

#159 채팅목록 정보 패치
  packages/client/src/atoms/Circle/index.tsx
  packages/client/src/common/utils.ts
  packages/client/src/components/Dialog/index.tsx
  packages/client/src/components/Loader/index.tsx
  packages/client/src/components/NavigationBar/AddFriendTab/index.tsx
  packages/client/src/components/NavigationBar/LogoutTab/index.tsx
  packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
  packages/client/src/components/RoomCard/index.tsx
  packages/client/src/components/RoomCard/styles.ts
  packages/client/src/modules/room/action.ts
  packages/client/src/modules/room/reducer.ts
  packages/client/src/modules/room/types.ts
  packages/client/src/modules/rootReducer.ts
  packages/client/src/modules/sagas/socketSaga.ts
  packages/client/src/pages/chatroom/ChatArea/ChatList/styles.ts
  packages/client/src/pages/chatroom/index.tsx
  packages/client/src/pages/main/index.tsx
  packages/client/src/pages/main/styles.ts
  packages/client/src/system/Profile/index.tsx
  packages/client/src/system/Room/index.tsx
  packages/client/src/system/Room/style.ts
  packages/common/src/types/modelTypes.ts
  packages/server/src/controllers/chat.ts
  packages/server/src/migrations/202004252134-create-chat.js
  packages/server/src/models/chat.ts
  packages/server/src/models/room.ts
  packages/server/src/seeders/20200505152211-chats.js
  packages/server/src/services/chat.ts
Labels: BE, FE, enhancement
